name: Build .deb package and add record in RELEASES tab
on:
  push:
    branches:
      - worlderp/master
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      #     Set global environment variables:
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0
      - name: Set global env
        id: global_env
        run: |
          releaseVersion=$(git tag -l | awk -F "v" '/v/{print $2}' | sort -nr | head -1)
          releaseFullVersion="v$(git tag -l | awk -F "v" '/v/{print $2}' | sort -nr | head -1)"
          echo "::set-output name=TARGET_BRANCH::worlderp/master"
          echo "::set-output name=PACKAGE_NAME::jigasi_$releaseVersion.deb"
          echo "::set-output name=RELEASE_FULL_VERSION::jigasi_$releaseVersion.deb"
          echo "::set-output name=RELEASE_VERSION_PART::$releaseVersion"
      - name: Set up JDK 11
        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#      - name: Build sources
#        run: |
#          mvn -DskipTests -Dassembly.skipAssembly=true package
#          mvn dependency:copy-dependencies -DincludeScope=runtime
      - name: Package .deb
        uses: olegbal/build-dpkg-buster@master
        with:
          version: ${{ steps.global_env.outputs.RELEASE_VERSION_PART }}
          build-args: -tc -us -uc -b -d -aamd64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.global_env.outputs.RELEASE_FULL_NAME }}
          files: |
            ${{ steps.global_env.outputs.PACKAGE_NAME }}